#!/bin/bash

cd /workspaces/documentation

# install python dependencies:
pip install -r requirements.txt

# Download PlantUML
curl -Lo /home/vscode/plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2022.7/plantuml-1.2022.7.jar

# install pre-commit hooks to git:
pre-commit install
